from homeassistant.const import Platform

DOMAIN = "chicken_house_master_module"
PLATFORMS: list[Platform] = [Platform.SENSOR]

DEVICE_MANUFACTURER = "Gautier Dumke"
DEVICE_MODEL = "Chicken House Maser Module"

CONF_NAME = "name"

CONF_SERIAL_PORT = "serial_port"
CONF_SERIAL_BAUDRATE = "serial_baudrate"
CONF_SERIAL_BAUDRATE_4800 = "4800"
CONF_SERIAL_BAUDRATE_9600 = "9600"
CONF_SERIAL_BAUDRATE_19200 = "19200"
CONF_SERIAL_BAUDRATE_57600 = "57600"
CONF_SERIAL_BAUDRATE_115200 = "115200"
CONF_SERIAL_BAUDRATE_DEFAULT = CONF_SERIAL_BAUDRATE_115200

CONF_SERIAL_BAUDRATES = [
    CONF_SERIAL_BAUDRATE_4800,
    CONF_SERIAL_BAUDRATE_9600,
    CONF_SERIAL_BAUDRATE_19200,
    CONF_SERIAL_BAUDRATE_57600,
    CONF_SERIAL_BAUDRATE_115200,
]

CONF_RF_CHANNEL = "rf_channel"
CONF_RF_CHANNEL_111 = "111"
CONF_RF_CHANNEL_124 = "124"
CONF_RF_CHANNEL_DEFAULT = CONF_RF_CHANNEL_111
CONF_RF_CHANNELS = [
    CONF_RF_CHANNEL_111,
    CONF_RF_CHANNEL_124,
]

CONF_RF_PALEVEL = "rf_pa_level"
CONF_RF_PALEVEL_MIN = "MIN"
CONF_RF_PALEVEL_LOW = "LOW"
CONF_RF_PALEVEL_HIGH = "HIGH"
CONF_RF_PALEVEL_MAX = "MAX"
CONF_RF_PALEVEL_DEFAULT = CONF_RF_PALEVEL_LOW
CONF_RF_PALEVELS = [
    CONF_RF_PALEVEL_MIN,
    CONF_RF_PALEVEL_LOW,
    CONF_RF_PALEVEL_HIGH,
    CONF_RF_PALEVEL_MAX,
]

CONF_RF_DATARATE = "rf_data_rate"
CONF_RF_DATARATE_250KBPS = "250KBPS"
CONF_RF_DATARATE_1MBPS = "1MBPS"
CONF_RF_DATARATE_2MBPS = "2MBPS"
CONF_RF_DATARATE_DEFAULT = CONF_RF_DATARATE_1MBPS
CONF_RF_DATARATES = [
    CONF_RF_DATARATE_250KBPS,
    CONF_RF_DATARATE_1MBPS,
    CONF_RF_DATARATE_2MBPS,
]
