# close_door:
#   name: Close the Chicken House door
#   description: Sends a message to the Chicken House slave module instructing to close the door
#   target:
#     entity:
#       integration: chicken_house_master_module
#   fields:
#     valeur_depart:
#       name: Valeur départ
#       description: La valeur de départ du compteur
#       required: false
#       advanced: false
#       example: "10"
#       default: "0"
#       selector:
#         number:
#           min: 0
#           max: 900
#           step: 1
#           mode: slider